apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-metrics
  namespace: prometheus
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - flink-bootcamp
  selector:
    matchLabels:
      app: advanced-app
  podMetricsEndpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
